pid tmp/{{GIN_ENV}}-nginx.pid;

# This number should be at maxium the number of CPU on the server
worker_processes 4;

events {
    # Number of connections per worker
    worker_connections 4096;
}

http {
    # use sendfile
    sendfile on;

    # Gin initialization
    {{GIN_INIT}}

    # for http traffic
    server {
        listen {{GIN_PORT}};

        keepalive_timeout 70;

        # Gin runtime
        {{GIN_RUNTIME}}

        # Access log with buffer, or disable it completetely if unneeded
        access_log logs/{{GIN_ENV}}-access.log combined buffer=16k;
        # Error log
        error_log logs/{{GIN_ENV}}-error.log debug;
    }
}
daemon off;
